[project]
name = 'tiny-market'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.moody-monkey]
path = 'contracts/moody-monkey.clar'
clarity_version = 2
epoch = 2.5


[contracts.sleepy-stripes]
path = 'contracts/sleepy-stripes.clar'
clarity_version = 2
epoch = 2.5


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
